### ISSUE TITLE
resetNetworkFork() failing in hardhat test

### ISSUE THREAD

**Issue by grapevinegizmos** [defi-org-code/web3-candies#3] opened 2021-10-26 22:11 UTC
Hello, when I include await resetNetworkFork() at the top of one of my tests, I get 
``` InvalidArgumentsError: Errors encountered in param 0: Invalid value undefined supplied to : HardhatNetworkConfig | undefined/forking: RpcForkConfig | undefined | undefined/jsonRpcUrl: string ```

Here is the top of one of my tests:

```      
        console.log("resetting local net")
        await resetNetworkFork();
        console.log("reset complete");
```
Here's what I get
```  
      resetting local net
      resetNetworkFork to latest
```
But no ```reset complete``` message

using hardhat v 2.6.3.  Here is my hardhat config if that's helpful:

```import {task} from "hardhat/config";
import '@typechain/hardhat'
import "@nomiclabs/hardhat-ethers";
import "@nomiclabs/hardhat-waffle";
import "@nomiclabs/hardhat-solhint";
import "hardhat-gas-reporter";
import "solidity-coverage";
import "hardhat-contract-sizer";
import "hardhat-tracer";

 
 


// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: {
    version: "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 1
      }
    }
  }, 
  networks: {
    hardhat: {
      initialBaseFeePerGas: 0, // workaround from https://github.com/sc-forks/solidity-coverage/issues/652#issuecomment-896330136 . Remove when that issue is closed.
    },
    ropsten: {
      url: process.env.ROPSTEN_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
  },
  gasReporter: {
   /* enabled: process.env.REPORT_GAS !== undefined,*/
    enabled: false,
    currency: "USD",
    coinmarketcap: "53712f5c-19c3-4b47-aa65-5794a2868056"
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};```

**Comment by DanielZlotin** [comment] 2022-01-12 16:42
You might be calling this too early, before Hardhat+web3 instances are ready.
When used in tests, you probably want to call it in `beforeEach(async() => await resetNetworkFork());`

closing as cant reproduce, reopen if needed

**Closed by DanielZlotin** 2022-01-12 16:42 UTC
